from .Add import Add
from .Div import Div
from .FAdd import FAdd
from .FDiv import FDiv
from .FImm import FImm
from .Flw import Flw
from .FMul import FMul
from .FMv import FMv
from .FNeg import FNeg
from .FSub import FSub
from .Fsw import Fsw
from .GetF import GetF
from .GetI import GetI
from .Halt import Halt
from .Instruction3O import Instruction3O
from .InstructionLS import InstructionLS
from .InstructionPut import InstructionPut
from .Instruction import Instruction
from .La import La
from .Li import Li
from .Lw import Lw
from .Mul import Mul
from .Mv import Mv
from .Neg import Neg
from .PutF import PutF
from .PutI import PutI
from .PutS import PutS
from .Sub import Sub
from .Sw import Sw
